name: ✨ Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if a similar feature has already been requested.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the use case?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this feature to work.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of the package does this affect?
      options:
        - New Webhook Service
        - Signature Validation
        - Logging & Dashboard
        - Notifications
        - Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: If applicable, provide a code example of how this feature might be used.
      render: php

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I would be willing to submit a PR for this feature
